### ISSUE TITLE
Using on Rpi Zero

### ISSUE THREAD

**Issue by HasibAlAhmed** [ShawnHymel/tflite-speech-recognition#5]
As the converted tf lite file can be executed in MCU. Can I somehow manage to run it in Raspberry Pi zero? Can you suggest me something for this?

**Comment by ShawnHymel** [comment]
This repo demonstrates how to run TFLite model files on a Raspberry Pi, so everything should work on an RPi Zero (it just might be slower).

**Comment by HasibAlAhmed** [comment]
Thanks for such a quick response.

**Comment by HasibAlAhmed** [comment]
I tried it on Raspberry Pi zero and it says
`"illegal instruction"`
when it tries to import interpreter from tflite_runtime

**Comment by ShawnHymel** [comment]
Hmmm...this might be due to the older processor on the Pi Zero (ARMv6 I think), which doesn't support some operations, like armhf (hardware floating point). See this discussion: [https://forums.raspberrypi.com/viewtopic.php?t=163212](https://forums.raspberrypi.com/viewtopic.php?t=163212). You'd probably need to disable armhf, but I'm not quite sure how to do that.

**Comment by HasibAlAhmed** [comment]
Thank you :(
I am fighting to fit this in RPi zero
